export const videoConstants = {

    REQUEST_CREATORS_VIDEOS: 'REQUEST_CREATORS_VIDEOS',
    RECEIVE_CREATORS_VIDEOS: 'RECEIVE_CREATORS_VIDEOS',
    ERROR_CREATORS_VIDEOS: 'ERROR_CREATORS_VIDEOS',

    UPDATE_CREATOR_VIDEOS: 'UPDATE_CREATOR_VIDEOS'

};
