export const fanoByteConstants = {
  REQUEST_GREETING_LISTING: 'REQUEST_GREETING_LISTING',
  RECEIVE_GREETING_LISTING: 'RECEIVE_GREETING_LISTING',
  ERROR_GREETING_LISTING: 'ERROR_GREETING_LISTING',

};
