export const photoConstants =
{
    REQUEST_CREATORS_PHOTOS: 'REQUEST_CREATORS_PHOTOS',
    RECEIVE_CREATORS_PHOTOS: 'RECEIVE_CREATORS_PHOTOS',
    ERROR_CREATORS_PHOTOS: 'ERROR_CREATORS_PHOTOS',

    REQUEST_ALBUM: 'REQUEST_ALBUM',
    RECEIVE_ALBUM: 'RECEIVE_ALBUM',
    ERROR_ALBUM: 'ERROR_ALBUM',

};
