export const profileConstants = {

    REQUEST_PROFILE_PAGE: 'REQUEST_PROFILE_PAGE',
    RECEIVE_PROFILE_PAGE: 'RECEIVE_PROFILE_PAGE',
    ERROR_PROFILE_PAGE: 'ERROR_PROFILE_PAGE',


    REQUEST_UPDATE_PROFILE: 'REQUEST_UPDATE_PROFILE',
    RECEIVE_UPDATE_PROFILE: 'RECEIVE_UPDATE_PROFILE',
    ERROR_UPDATE_PROFILE: 'ERROR_UPDATE_PROFILE',


};
