
export const Icons = {
    hamburger: '/icons/hamburger.svg',
    fb: '/icons/fb.svg',
    google: '/icons/google.svg',
    share: '/icons/share.svg',
    comment: '/icons/comment.svg',
    heart: '/icons/heart.svg',
    token: '/icons/token.png',
    coin: '/icons/fan-level.png',
    bronze: '/icons/bronze-coin.svg',
    gold: '/icons/gold-coin.svg',
    silver: '/icons/silver-coin.svg',
    logout: '/icons/logout.svg',
    filter: '/icons/filter.svg',
    copy: '/icons/copy.svg',
    stopWatch: '/stop-watch.svg',
    star: '/star.png',
    call: '/icons/call.png',
    superfan: '/icons/superfan.png',
    superSend: '/icons/superSend.png',
    gift: '/icons/gift.svg',
    fanBoy: "/icons/frame.png",
    disconnectCall: "/icons/disconnect.png",
    mic: "/icons/mic.svg",
    camChat: "/icons/cam-chat.svg",
    love: "/icons/love.svg",
    sendRequest: "/icons/sendRequest.svg",
    receiveVideo: "/icons/receiveVideo.svg",
    reload: "/icons/reload.svg",
    down: "/icons/down.svg",
    infoCircle: "/icons/infoCircle.svg",
    silvercoin:"/icons/fanory_silver.png",
    smcoins:"/icons/coins.png"
};
