const Routes = {
  login: (creator: string) => `/${creator}/login`,
  loginWithDestination: (creator: string, destination: string) => `/${creator}/login?destination=${destination}`,
  loginVerification: (creator: string, mobile: string, code: string) => `/${creator}/verification?mobile=${Buffer.from(mobile).toString('base64')}&code=${encodeURIComponent(code)}`,
  loginVerificationWithDestination: (creator: string, mobile: string, code: string, destination: string) => `/${creator}/verification?mobile=${mobile}&code=${encodeURIComponent(code)}&destination=${destination}`,
  home: (creator: string) => `/${creator}`,
  content: (creator: string, destination: string) => `/${creator}/${destination}`,
  photos: (creator: string) => `/${creator}/photos`,
  videos: (creator: string) => `/${creator}/videos`,
  comments: (creator: string, contentId: string) => `/${creator}/comments/${contentId}`,
  reply: (creator: string, contentId: string, commentId: string) => `/${creator}/comments/${contentId}/reply/${commentId}`,
  videoCall: (creator: string) => `/${creator}/video-call`,
  videoCallRequests: (creator: string) => `/${creator}/video-call/my-requests`,
  videoCallBooking: (creator: string) => `/${creator}/video-call/booking`,
  fanoByteBooking: (creator: string) => `/${creator}/fanobyte/booking`,
  fanoByteRequests: (creator: string) => `/${creator}/fanobyte/my-requests`,
  directLine: (creator: string) => `/${creator}/direct-line`,
  wardrobeOrders: (creator: string) => `/${creator}/wardrobe/my-orders`,
  celeByte: (creator: string) => `/${creator}/video-call/celebyte`,
  joinCall: (creator: string) => `/${creator}/video-call/join`,
  profile: (creator: string) => `/${creator}/profile`,
  wallet: (creator: string) => `/${creator}/wallet`,
  editProfile: (creator: string) => `/${creator}/profile/edit`,
  recharge: (creator: string) => `/${creator}/recharge`,
  faq: process.env.NEXT_PUBLIC_STATIC_PAGE_URL+'faq',
  termsUse: process.env.NEXT_PUBLIC_STATIC_PAGE_URL+'terms-conditions-fanory',
  privacyPolicy: process.env.NEXT_PUBLIC_STATIC_PAGE_URL+'privacy-policy',
  copyRight: process.env.NEXT_PUBLIC_STATIC_PAGE_URL+'copyright-infriginment-policy',
  cancellationRefundPolicy : process.env.NEXT_PUBLIC_STATIC_PAGE_URL+'copyright-infriginment-policy',
};
export default Routes;
