export const callConstants = {
  REQUEST_VIDEO_CALL_REQUEST: 'REQUEST_VIDEO_CALL_REQUEST',
  RECEIVE_VIDEO_CALL_REQUEST: 'RECEIVE_VIDEO_CALL_REQUEST',
  ERROR_VIDEO_CALL_REQUEST: 'ERROR_VIDEO_CALL_REQUEST',

};
