export const liveConstants = {

    REQUEST_UPCOMING_LIVE : 'REQUEST_UPCOMING_LIVE',
    RECEIVE_UPCOMING_LIVE : 'RECEIVE_UPCOMING_LIVE',
    ERROR_UPCOMING_LIVE : 'ERROR_UPCOMING_LIVE',

    REQUEST_JOIN_LIVE: 'REQUEST_JOIN_LIVE',
    RECEIVE_JOIN_LIVE: 'RECEIVE_JOIN_LIVE',
    ERROR_JOIN_LIVE: 'ERROR_JOIN_LIVE',

    REQUEST_SUPERSEND: 'REQUEST_SUPERSEND',
    RECEIVE_SUPERSEND: 'RECEIVE_SUPERSEND',
    ERROR_SUPERSEND: 'ERROR_SUPERSEND',

    REQUEST_GET_GIFT: "REQUEST_GET_GIFT",
    RECEIVE_GET_GIFT: "RECEIVE_GET_GIFT",
    ERROR_GET_GIFT: "ERROR_GET_GIFT",

};
