export const wardrobeConstants = {
    REQUEST_WARDROBE_LISTING: 'REQUEST_WARDROBE_LISTING',
    RECEIVE_WARDROBE_LISTING: 'RECEIVE_WARDROBE_LISTING',
    ERROR_WARDROBE_LISTING: 'ERROR_WARDROBE_LISTING',

    REQUEST_WARDROBE: 'REQUEST_WARDROBE',
    RECEIVE_WARDROBE: 'RECEIVE_WARDROBE',
    ERROR_WARDROBE: 'ERROR_WARDROBE',

    REQUEST_WARDROBE_ORDERS_LISTING: 'REQUEST_WARDROBE_ORDERS_LISTING',
    RECEIVE_WARDROBE_ORDERS_LISTING: 'RECEIVE_WARDROBE_ORDERS_LISTING',
    ERROR_WARDROBE_ORDERS_LISTING: 'ERROR_WARDROBE_ORDERS_LISTING',
};
