export const commentConstants = {
    REQUEST_COMMENTS_LISTING: 'REQUEST_COMMENTS_LISTING',
    RECEIVE_COMMENTS_LISTING: 'RECEIVE_COMMENTS_LISTING',
    ERROR_COMMENTS_LISTING: 'ERROR_COMMENTS_LISTING',
    UPDATE_COMMENTS : 'UPDATE_COMMENTS',
    UPDATE_REPLY: 'UPDATE_REPLY',
};
