export const transactionConstants = {

    REQUEST_WALLET_PAGE: 'REQUEST_WALLET_PAGE',
    RECEIVE_WALLET_PAGE: 'RECEIVE_WALLET_PAGE',
    ERROR_WALLET_PAGE: 'ERROR_WALLET_PAGE',


    REQUEST_RECHARGE_PAGE: 'REQUEST_RECHARGE_PAGE',
    RECEIVE_RECHARGE_PAGE: 'RECEIVE_RECHARGE_PAGE',
    ERROR_RECHARGE_PAGE: 'ERROR_RECHARGE_PAGE',

    REQUEST_ORDERS: 'REQUEST_ORDERS',
    RECEIVE_ORDERS: 'RECEIVE_ORDERS',
    ERROR_ORDERS: 'ERROR_ORDERS',

};
